### ISSUE TITLE
General use of install-fns

### ISSUE THREAD

**Issue by cldwalker** [alandipert/mathemagician#7]
Any objections to making install-fns public for other java.lang.\* classes?

**Comment by qtrfeast** [comment]
@alandipert had expressed concern that install-fns would not play nicely with overloaded functions. I believe Math in particular was OK, but it could be an issue for other classes.

@alandipert?

**Comment by alandipert** [comment]
Sure, but I think it would be better to spin off install-fns into its own library and then consume it, since install-fns has nothing necessarily to do with math, and mathemagician's behavior is well defined.  Who wants the glory?

Edit: On second thought, let's just keep rolling!
